### ISSUE TITLE
Fatal error: error writing to -: Broken pipe

### ISSUE THREAD

**Issue by perdugames** [jrimclean/gdnet#6]
I'm getting this error when trying to compile in godot 3:

```
Assembler messages:
Fatal error: can't create modules/gdnet/enet/packet.x11.tools.64.o: Permission denied
modules/gdnet/enet/packet.cpp:163:1: fatal error: error writing to -: Broken pipe
 }
 ^
compilation terminated.
scons: *** [modules/gdnet/enet/packet.x11.tools.64.o] Error 1
scons: building terminated because of errors.

```

**Comment by empyreanx** [comment]
Which compiler and platform are you using? I just verified that master compiles with G++ 5.4.0.

**Comment by empyreanx** [comment]
This looks like a permissions issue, closing...
